server:
  port: 9001

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost/bc_131_checkr_db?serverTimezone=UTC
    username: bc131
    password: bc131@
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    baseline-on-migrate: true
    locations: classpath:/db/migration
    validate-on-migrate: false
    enabled: true
    out-of-order: true
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost

jwt:
  secret: d2fbb1d0e2fcb4e8c4b1c4e8d1fbb1d0e2fcb4e8c4b1c4e8d1fbb1d0e2fcb4e8c4b1c4e8

token:
  expiry:
    time: 86400

candidates:
  url: http://localhost:9002/api/v1/candidates/save-candidates
