server:
  port: 9003

spring:
  application:
    name: ADVERSE-ACTION-SERVICE
  datasource:
    url: jdbc:mysql://localhost/bc_131_checkr_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    baseline-on-migrate: true
    locations: classpath:/db/migration
    validate-on-migrate: false
    enabled: true
    out-of-order: true
    ignore-missing-migrations: true
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${SERVICE_REGISTRY_URL}
    instance:
      hostname: localhost